#!/usr/bin/env python3
"""Build the About page's filmstrip from the tiles on the front page.

The About page opened as a wall of text on a film director's site. This is a
band of real frames from his own work — monochrome at rest like the rest of
the archive, developing to colour when engaged, each linking to that film's
page. Derived from index.html so it can never drift from the work itself.
"""
import re, sys, html

SRC = open('index.html').read()

# Landscape frames only — a strip of 16:9 gates, mixed so the range reads:
# Sudan documentary next to global commercial work.
WANT = ['The Greatest Sudanese Sit-In', 'Solana Accelerate', 'Sia x Solana',
        'Solana Skyline', '60 Secs of New York', 'Crypto in the UAE']

def slugify(t):
    t = html.unescape(t).lower().replace('&', ' and ').replace('“','').replace('”','').replace('"','')
    return re.sub(r'[^a-z0-9]+', '-', t).strip('-')

frames = []
for b in re.findall(r'<article class="tile[\s\S]+?</article>', SRC):
    title = (re.search(r'data-title="([^"]+)"', b) or [None, ''])[1]
    if html.unescape(title) not in WANT:
        continue
    poster = re.search(r'srcset="(assets/posters/[^ ]+-768\.jpg\?h=[a-f0-9]+)', b)
    full   = re.search(r'\bsrc="(assets/posters/[^"]+)"', b)
    if not full:
        sys.exit('no poster for ' + title)
    frames.append({
        'title': title,
        'slug': slugify(title),
        'small': poster.group(1) if poster else full.group(1),
        'full': full.group(1),
        'kind': (re.search(r'tile__kind">([^<]*)<', b) or [None, ''])[1],
    })

frames.sort(key=lambda f: WANT.index(html.unescape(f['title'])))
if len(frames) != len(WANT):
    sys.exit(f'wanted {len(WANT)} frames, matched {len(frames)}')

items = ''.join(f'''
      <a class="reel__frame" href="/work/{f['slug']}" aria-label="{html.escape(html.unescape(f['title']), quote=True)} — {html.unescape(f['kind'])}">
        <img src="/{f['small']}" alt="Still from {f['title']}" width="768" height="432" loading="lazy" decoding="async">
        <span class="reel__label">{f['title']}</span>
      </a>''' for f in frames)

strip = f'''
  <!-- Frames from his own films: monochrome at rest like the rest of the
       archive, colour when engaged. Generated by bin-build-about-strip.py
       from the tiles on the front page — never hand-maintained. -->
  <section class="reel" aria-label="Frames from selected films">
    <div class="reel__track">{items}
    </div>
    <p class="reel__note"><a href="/work/">All sixteen films &rarr;</a></p>
  </section>
'''

page = open('about.html').read()
page = re.sub(r'\n *<!-- Frames from his own films[\s\S]*?</section>\n', '\n', page)
anchor = '''    <p class="pagehead__act"><a class="btn btn--ghost" href="assets/Ahmed_ElNimeri_CV.pdf?h=15dd1130">Download CV (PDF)</a></p>
  </section>
'''
if anchor not in page:
    sys.exit('pagehead anchor not found')
page = page.replace(anchor, anchor + strip, 1)
open('about.html', 'w').write(page)
print(f'about strip: {len(frames)} frames — ' + ', '.join(html.unescape(f['title']) for f in frames))
