#!/usr/bin/env python3
"""Render the 'What people say' block on /about from assets/reception.json.

The quotes live in one file so the site, the applications document and the
raw harvest can never drift apart. This script rewrites only what sits
between the two markers in about.html, so the rest of the page is untouched
and re-running it is safe.

Only comments addressed to Ahmed or to the work are in that file. The threads
they came from also carry grief and politics, which are not this site's to
reprint — see the note at the top of reception.json.
"""
import json, re, html, sys

START = '<!-- SAID:START (generated by bin-build-about-said.py) -->'
END = '<!-- SAID:END -->'

rec = json.load(open('assets/reception.json'))
quotes = rec.get('about', {}).get('quotes', [])
if not quotes:
    sys.exit('no quotes under "about" in assets/reception.json')

cards = []
for q in quotes:
    ar, en, by = q.get('ar', '').strip(), q['en'].strip(), q['by']
    where = q.get('where', '')
    arline = '' if (not ar or ar == en) else \
        f'<p class="said__ar" lang="ar" dir="rtl">{html.escape(ar)}</p>'
    meta = html.escape(by) + (f' &middot; {html.escape(where)}' if where else '')
    cards.append(f'<figure class="said">{arline}'
                 f'<blockquote class="said__en">{html.escape(en)}</blockquote>'
                 f'<figcaption class="said__by">{meta}</figcaption></figure>')

block = f'''{START}
  <section class="section" id="said">
    <div class="slate">
      <span class="slate__tc" data-tc>TC 38:00:00</span>
      <h2 class="slate__title">What people say</h2>
      <span class="slate__meta">006 &middot; {len(cards)} comments</span>
    </div>
    <p class="reception__sub">Unedited public comments, from the posts themselves. Arabic as written,
      with a translation. Nothing here was solicited.</p>
    <div class="reception__grid">{''.join(cards)}</div>
  </section>
  {END}'''

page = open('about.html').read()
if START in page:
    page = re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END), block, page, count=1)
else:
    anchor = '  <section class="contact" id="contact">'
    if anchor not in page:
        sys.exit('could not find the contact section to insert before')
    page = page.replace(anchor, block + '\n\n' + anchor, 1)
open('about.html', 'w').write(page)
print(f'about.html: {len(cards)} comments in the What people say block')
