#!/usr/bin/env python3
"""Render About section 006, On Set, from assets/onset.json.

The board groups the frames by the year they were taken, in the order they
happened, and lays each print out by its "shape" (wide, tall, mid, half,
full). Typed by hand the grouping drifts the moment a frame is added, so it is
derived here from one list.

  python3 bin-build-onset.py seed                      # write assets/onset.json from about.html (once)
  python3 bin-build-onset.py grade SRC NAME [GRAVITY]  # grade a photo into assets/onset/NAME(.jpg|-700.jpg)
  python3 bin-build-onset.py                           # render about.html from assets/onset.json

Every year is what the frame's date really is: EXIF DateTimeOriginal where the
camera kept honest time, Ahmed's word where it did not. Captions describe the
frame, never name a person. Run bin-stamp-assets.py afterwards.
"""
import re, json, sys, html, subprocess, os

PAGE, DATA = 'about.html', 'assets/onset.json'
START = '<!-- ONSET:START (generated by bin-build-onset.py) -->'
END = '<!-- ONSET:END -->'
esc = lambda s: html.escape(s, quote=True)

def section(page):
    s = page.index('<section class="section" id="onset">')
    return s, page.index('</section>', s)

def seed():
    page = open(PAGE).read(); s, e = section(page); sec = page[s:e]
    frames = []
    for f in re.findall(r'<figure class="os-fr"[\s\S]*?</figure>', sec):
        name = re.search(r'src="assets/onset/([^".?]+)\.jpg', f).group(1)
        alt = html.unescape(re.search(r'alt="([^"]*)"', f).group(1))
        year = int(re.search(r'os-fr__yr">(\d{4})<', f).group(1))
        label = html.unescape(re.search(r'os-fr__lbl">([^<]*)<', f).group(1))
        frames.append(dict(name=name, year=year, label=label, alt=alt))
    assert frames, 'no frames found'
    json.dump(dict(frames=frames), open(DATA, 'w'), indent=1, ensure_ascii=False)
    open(DATA, 'a').write('\n')
    print(f'{DATA}: {len(frames)} frames seeded')

def grade(src, name, gravity='center'):
    base = ['magick', src, '-auto-orient']
    look = ['-colorspace', 'Gray', '-sigmoidal-contrast', '3,50%', '-modulate', '104,0,100',
            '-unsharp', '0x0.7+0.5+0.02', '-strip', '-quality', '86']
    for w, h, suffix in ((1200, 800, ''), (700, 467, '-700')):
        out = f'assets/onset/{name}{suffix}.jpg'
        subprocess.run(base + ['-resize', f'{w}x{h}^', '-gravity', gravity, '-extent', f'{w}x{h}'] + look + [out], check=True)
        print('wrote', out)

# How each print sits on the board. "shape" in assets/onset.json picks one;
# "focus" is the object-position for crops that lose part of the frame (tall).
SHAPES = {
    'wide': '(max-width: 700px) 100vw, 46vw',
    'tall': '(max-width: 700px) 50vw, 31vw',
    'mid':  '(max-width: 700px) 50vw, 38vw',
    'half': '(max-width: 700px) 100vw, 38vw',
    'full': '(max-width: 700px) 100vw, 78vw',
}

def render(frames):
    # One group per year, in the order the frames happened. Groups of three
    # alternate which side the tall print stands on, so the board never
    # repeats itself down the page.
    groups = []
    for f in frames:
        if groups and groups[-1][0] == f['year']:
            groups[-1][1].append(f)
        else:
            groups.append((f['year'], [f]))
    out, flip = [], False
    for year, fs in groups:
        cls = ''
        if any(f.get('shape') == 'tall' for f in fs):
            cls = ' set__group--flip' if flip else ''
            flip = not flip
        prints = []
        for f in fs:
            shape = f.get('shape', 'mid')
            if shape not in SHAPES: sys.exit(f"unknown shape {shape!r} for {f['name']}")
            name = f['name']
            pos = f' style="object-position: {esc(f["focus"])}"' if f.get('focus') else ''
            prints.append(f'''          <figure class="set__print set__print--{shape}">
            <div class="set__win"><img class="set__img" src="assets/onset/{name}-700.jpg"
                 srcset="assets/onset/{name}-700.jpg 700w, assets/onset/{name}.jpg 1200w"
                 sizes="{SHAPES[shape]}"
                 alt="{esc(f['alt'])}" width="1200" height="800"{pos}
                 loading="lazy" decoding="async"></div>
            <figcaption class="set__cap">{esc(f['label'])}</figcaption>
          </figure>''')
        out.append(f'''      <div class="set__group{cls}">
        <h3 class="set__yr">{year}</h3>
        <div class="set__prints">
{chr(10).join(prints)}
        </div>
      </div>''')
    return f'''{START}
    <div class="set">
{chr(10).join(out)}
    </div>
    {END}
'''

def build():
    frames = json.load(open(DATA))['frames']
    for f in frames:
        for suffix in ('', '-700'):
            p = f"assets/onset/{f['name']}{suffix}.jpg"
            if not os.path.exists(p): sys.exit(f'missing {p}')
    page = open(PAGE).read(); s, e = section(page); sec = page[s:e]
    block = render(frames)
    if START in sec:
        new = re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END) + r'\n?', lambda m: block, sec, count=1)
    else:
        a = sec.index('    <div class="set"')
        new = sec[:a] + block + '  '
    out = page[:s] + new + page[e:]
    # assert the RESULT, not the precondition
    sec2 = out[out.index('<section class="section" id="onset">'):]
    sec2 = sec2[:sec2.index('</section>')]
    assert sec2.count('<figure class="set__print') == len(frames)
    assert sec2.count(START) == 1 and sec2.count(END) == 1
    open(PAGE, 'w').write(out)
    yrs = [f['year'] for f in frames]
    print(f'{PAGE}: On Set rendered — {len(frames)} frames, {min(yrs)}–{max(yrs)}')

if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'build'
    if cmd == 'seed': seed()
    elif cmd == 'grade': grade(*sys.argv[2:5])
    else: build()
