#!/usr/bin/env python3
"""Render 'Comments' on /about from assets/reception.json.

Two registers, because the material has two kinds. The short comments are a
crowd — their force is in the number of them and in how fast they land, so
they drift past on two counter-running strips, the same mechanism the client
logos use, and a visitor reads twenty of them in the time it takes to read
one. The long ones are arguments about the work, so they sit still as cards
with the Arabic as written above the translation.

Everything between the two markers is regenerated, so re-running is safe and
the rest of about.html is untouched.
"""
import json, re, html, sys, os

START = '<!-- SAID:START (generated by bin-build-about-said.py) -->'
END = '<!-- SAID:END -->'
SHORT = 58          # an English line short enough to read while it moves

rec = json.load(open('assets/reception.json'))
all_quotes = rec.get('about', {}).get('quotes', [])
# A quote on hold came from a private channel and has not been cleared by the
# person who wrote it. It stays in the file, and off the site, until it has.
quotes = [q for q in all_quotes if not q.get('hold')]
held = len(all_quotes) - len(quotes)
if not quotes:
    sys.exit('no publishable quotes under "about" in assets/reception.json')

# A featured quote always gets a card and always leads, whatever its length —
# a named person with a title at a real company carries further than a handle.
feature = [q for q in quotes if q.get('feature')]
rest = [q for q in quotes if not q.get('feature')]
short = [q for q in rest if len(q['en']) <= SHORT]
long_ = [q for q in rest if len(q['en']) > SHORT]
long_.sort(key=lambda q: -len(q['en']))
if len(short) < 8:
    sys.exit(f'only {len(short)} short quotes — the strips need more than that')

# The site shows the translation only. The Arabic stays in reception.json,
# where the applications document reads it — it is the original, and losing it
# would lose the evidence.
AR_SCRIPT = re.compile('[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]')

def named(t):
    """A name written in Arabic script is marked as Arabic, so a screen reader
    does not read it with an English voice. Inline, so nothing moves; isolated
    (dir=auto) only when the name has no Latin letters, so a mixed name keeps
    the order it is shown in today."""
    if not AR_SCRIPT.search(t):
        return t
    return '<span lang="ar"' + ('' if re.search('[A-Za-z]', t) else ' dir="auto"') + '>' + t + '</span>'

def pill(q):
    return (f'<span class="say"><span class="say__t">{html.escape(q["en"])}</span>'
            f'<span class="say__u">{named(html.escape(q["by"]))}</span></span>')

def card(q, n=0):
    en, by = q['en'].strip(), q['by']
    where = q.get('where', '')
    cls = ' said--lead' if q.get('feature') else ''
    meta = named(html.escape(by)) + (f' &middot; {html.escape(where)}' if where else '')
    body = html.escape(en)
    # A quote about one film ("film": its page's slug and title) leads to
    # it: the film's name in the quote becomes the link, or, where the quote
    # does not name it, the caption carries it.
    film = q.get('film')
    if film:
        if not os.path.exists(f"work/{film['slug']}.html"):
            sys.exit(f"assets/reception.json: no film page work/{film['slug']}.html for a quote by {by}")
        t = html.escape(film['title'])
        link = f'<a class="said__film" href="/work/{film["slug"]}">{t}</a>'
        if t in body:
            body = body.replace(t, link, 1)
        else:
            meta += f' &middot; {link}'
    # Cards arrive with the site's own reveal, a beat apart across a row.
    return (f'<figure class="said{cls} reveal" data-delay="{(n % 3) * 90}">'
            f'<blockquote class="said__en">{body}</blockquote>'
            f'<figcaption class="said__by">{meta}</figcaption></figure>')

# Split the strips so neither row repeats the other, and so each row is long
# enough that the loop point never lands inside the viewport.
a, b = short[0::2], short[1::2]
def strip(items, cls):
    run = ''.join(pill(q) for q in items)
    return (f'<div class="says__row{cls}">'
            f'<div class="says__track">{run}</div>'
            f'<div class="says__track" aria-hidden="true">{run}</div></div>')

wheres = []
for q in quotes:
    w = q.get('where')
    if w and w not in wheres:
        wheres.append(w)

# "Facebook, X, Instagram and TikTok": the places the comments were posted,
# in the order they first appear in the file
WHERE = ', '.join(wheres[:-1]) + ' and ' + wheres[-1] if len(wheres) > 1 else ''.join(wheres)

# A quote with no "where" was not posted anywhere: it reached Ahmed directly
# (reception.json about._published: the two named executives, published as
# they are, the channel label off at his request). The intro does not call
# those public.
direct = [q for q in quotes if not q.get('where')]
_N = ['no', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
if direct:
    INTRO = (f'Comments, unedited: public ones from {WHERE}, and '
             f'{_N[len(direct)] if len(direct) < len(_N) else len(direct)} sent to me directly.')
else:
    INTRO = f'Public comments, unedited, from {WHERE}.'

# The named voices with a title at a real company lead, in a row of their own.
leads = (f'<div class="said-leads">{"".join(card(q, n) for n, q in enumerate(feature))}</div>'
         if feature else '')

block = f'''{START}
  <section class="section" id="said">
    <div class="slate">
      <h2 class="slate__title">Comments</h2>
    </div>
    <p class="reception__sub">{INTRO}
      Comments written in Arabic are shown in translation.</p>
    <div class="says" aria-label="Comments">
      {strip(a, '')}
      {strip(b, ' says__row--back')}
    </div>
    {leads}
    <div class="said-wall">{''.join(card(q, n) for n, q in enumerate(long_))}</div>
  </section>
  {END}'''

page = open('about.html').read()
if START in page:
    page = re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END), lambda m: block, page, count=1)
else:
    anchor = '  <section class="contact" id="contact">'
    if anchor not in page:
        sys.exit('could not find the contact section to insert before')
    page = page.replace(anchor, block + '\n\n' + anchor, 1)
open('about.html', 'w').write(page)
print(f'about.html: {len(short)} on the strips, {len(feature) + len(long_)} as cards, {len(quotes)} published'
      + (f', {held} held' if held else '')
      + (f', {len(feature)} featured' if feature else ''))
