#!/usr/bin/env python3
"""Render About section 006, On Set, from assets/onset.json.

The gate's markup carries numbers that must agree with the frames: the frame
count in the rail and on the slate, the year span, one tick per frame, one year
cell per distinct year, and the pin length. Typed by hand they drift the moment a
frame is added, so they are derived here from one list.

  python3 bin-build-onset.py seed                      # write assets/onset.json from about.html (once)
  python3 bin-build-onset.py grade SRC NAME [GRAVITY]  # grade a photo into assets/onset/NAME(.jpg|-700.jpg)
  python3 bin-build-onset.py                           # render about.html from assets/onset.json

Every year is what the frame's date really is: EXIF DateTimeOriginal where the
camera kept honest time, Ahmed's word where it did not. Captions describe the
frame, never name a person. Run bin-stamp-assets.py afterwards.
"""
import re, json, sys, html, subprocess, os

PAGE, DATA = 'about.html', 'assets/onset.json'
START = '<!-- ONSET:START (generated by bin-build-onset.py) -->'
END = '<!-- ONSET:END -->'
esc = lambda s: html.escape(s, quote=True)

def section(page):
    s = page.index('<section class="section" id="onset">')
    return s, page.index('</section>', s)

def seed():
    page = open(PAGE).read(); s, e = section(page); sec = page[s:e]
    frames = []
    for f in re.findall(r'<figure class="os-fr"[\s\S]*?</figure>', sec):
        name = re.search(r'src="assets/onset/([^".?]+)\.jpg', f).group(1)
        alt = html.unescape(re.search(r'alt="([^"]*)"', f).group(1))
        year = int(re.search(r'os-fr__yr">(\d{4})<', f).group(1))
        label = html.unescape(re.search(r'os-fr__lbl">([^<]*)<', f).group(1))
        frames.append(dict(name=name, year=year, label=label, alt=alt))
    assert frames, 'no frames found'
    json.dump(dict(frames=frames), open(DATA, 'w'), indent=1, ensure_ascii=False)
    open(DATA, 'a').write('\n')
    print(f'{DATA}: {len(frames)} frames seeded')

def grade(src, name, gravity='center'):
    base = ['magick', src, '-auto-orient']
    look = ['-colorspace', 'Gray', '-sigmoidal-contrast', '3,50%', '-modulate', '104,0,100',
            '-unsharp', '0x0.7+0.5+0.02', '-strip', '-quality', '86']
    for w, h, suffix in ((1200, 800, ''), (700, 467, '-700')):
        out = f'assets/onset/{name}{suffix}.jpg'
        subprocess.run(base + ['-resize', f'{w}x{h}^', '-gravity', gravity, '-extent', f'{w}x{h}'] + look + [out], check=True)
        print('wrote', out)

def render(frames):
    n = len(frames)
    yy = []
    for f in frames:
        c = str(f['year'])[2:]
        if c not in yy: yy.append(c)
    cells = ''.join(f'<span>{i + 1:02d}</span>' for i in range(n))
    ycells = ''.join(f'<span>{c}</span>' for c in yy)
    figs, ticks = [], []
    for i, f in enumerate(frames):
        no = f'{i + 1:02d}'; name = f['name']
        figs.append(f'''              <figure class="os-fr" data-os-yr="{str(f['year'])[2:]}">
                <div class="os-fr__win"><img class="os-fr__img" src="assets/onset/{name}.jpg"
                     srcset="assets/onset/{name}-700.jpg 700w, assets/onset/{name}.jpg 1200w"
                     sizes="(max-width: 900px) 100vw, 70vw"
                     alt="{esc(f['alt'])}" width="1200" height="800"
                     loading="{'eager' if i < 3 else 'lazy'}" decoding="async"></div>
                <figcaption class="os-fr__cap"><span class="os-fr__no">FR {no}</span><span class="os-fr__yr">{f['year']}</span><span class="os-fr__lbl">{esc(f['label'])}</span></figcaption>
              </figure>''')
        ticks.append(f'''            <button class="os-tick" type="button" aria-label="Frame {no}, {f['year']}, {esc(f['label'])}"><span class="os-tick__no" aria-hidden="true">{no}</span><span class="os-tick__bar"><span class="os-tick__fill"></span></span></button>''')
    return f'''{START}
    <div class="os-stage" style="--os-n: {n}">
      <div class="os-pin">
        <div class="os-gate">
          <div class="os-screen">

            <div class="os-rail" aria-hidden="true">
              <div>
                <span class="os-rail__k">Frame</span>
                <span class="os-count"><span class="os-win"><span class="os-reel" data-os-reel="no">{cells}</span></span></span>
                <span class="os-rail__k">of {n:02d}</span>
              </div>
              <div>
                <span class="os-rail__k">Year</span>
                <span class="os-year"><span>20</span><span class="os-win"><span class="os-reel" data-os-reel="yr">{ycells}</span></span></span>
              </div>
            </div>

            <div class="os-frames">
{chr(10).join(figs)}
            </div>
          </div>

          <div class="os-ticks" role="group" aria-label="Go to frame">
{chr(10).join(ticks)}
          </div>
        </div>
      </div>
    </div>
    {END}
'''

def build():
    frames = json.load(open(DATA))['frames']
    for f in frames:
        for suffix in ('', '-700'):
            p = f"assets/onset/{f['name']}{suffix}.jpg"
            if not os.path.exists(p): sys.exit(f'missing {p}')
    page = open(PAGE).read(); s, e = section(page); sec = page[s:e]
    block = render(frames)
    if START in sec:
        new = re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END) + r'\n?', lambda m: block, sec, count=1)
    else:
        a = sec.index('    <div class="os-stage"')
        new = sec[:a] + block + '  '
    yrs = [f['year'] for f in frames]
    new, k = re.subn(r'(<span class="slate__meta">\d{3} &middot; )\d+ frames &middot; \d{4}&ndash;\d{4}(</span>)',
                     lambda m: f'{m.group(1)}{len(frames)} frames &middot; {min(yrs)}&ndash;{max(yrs)}{m.group(2)}', new, count=1)
    assert k == 1, 'slate meta not found'
    out = page[:s] + new + page[e:]
    # assert the RESULT, not the precondition
    sec2 = out[out.index('<section class="section" id="onset">'):]
    sec2 = sec2[:sec2.index('</section>')]
    assert sec2.count('<figure class="os-fr"') == len(frames) and sec2.count('class="os-tick"') == len(frames)
    assert sec2.count(START) == 1 and sec2.count(END) == 1
    open(PAGE, 'w').write(out)
    print(f'{PAGE}: On Set rendered — {len(frames)} frames, {min(yrs)}–{max(yrs)}')

if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'build'
    if cmd == 'seed': seed()
    elif cmd == 'grade': grade(*sys.argv[2:5])
    else: build()
