#!/usr/bin/env python3
"""Render 'What people say' on /about from assets/reception.json.

Two registers, because the material has two kinds. The short comments are a
crowd — their force is in the number of them and in how fast they land, so
they drift past on two counter-running strips, the same mechanism the client
logos use, and a visitor reads twenty of them in the time it takes to read
one. The long ones are arguments about the work, so they sit still as cards
with the Arabic as written above the translation.

Everything between the two markers is regenerated, so re-running is safe and
the rest of about.html is untouched.
"""
import json, re, html, sys

START = '<!-- SAID:START (generated by bin-build-about-said.py) -->'
END = '<!-- SAID:END -->'
SHORT = 58          # an English line short enough to read while it moves

rec = json.load(open('assets/reception.json'))
quotes = rec.get('about', {}).get('quotes', [])
if not quotes:
    sys.exit('no quotes under "about" in assets/reception.json')

short = [q for q in quotes if len(q['en']) <= SHORT]
long_ = [q for q in quotes if len(q['en']) > SHORT]
long_.sort(key=lambda q: -len(q['en']))
if len(short) < 8:
    sys.exit(f'only {len(short)} short quotes — the strips need more than that')

def pill(q):
    ar = q.get('ar', '').strip()
    mark = '<span class="say__ar" aria-hidden="true">ع</span>' if ar and ar != q['en'] else ''
    return (f'<span class="say"><span class="say__t">{html.escape(q["en"])}</span>'
            f'{mark}<span class="say__u">{html.escape(q["by"])}</span></span>')

def card(q):
    ar, en, by = q.get('ar', '').strip(), q['en'].strip(), q['by']
    where = q.get('where', '')
    arline = '' if (not ar or ar == en) else \
        f'<p class="said__ar" lang="ar" dir="rtl">{html.escape(ar)}</p>'
    meta = html.escape(by) + (f' &middot; {html.escape(where)}' if where else '')
    return (f'<figure class="said">{arline}'
            f'<blockquote class="said__en">{html.escape(en)}</blockquote>'
            f'<figcaption class="said__by">{meta}</figcaption></figure>')

# Split the strips so neither row repeats the other, and so each row is long
# enough that the loop point never lands inside the viewport.
a, b = short[0::2], short[1::2]
def strip(items, cls):
    run = ''.join(pill(q) for q in items)
    return (f'<div class="says__row{cls}">'
            f'<div class="says__track">{run}</div>'
            f'<div class="says__track" aria-hidden="true">{run}</div></div>')

wheres = []
for q in quotes:
    w = q.get('where')
    if w and w not in wheres:
        wheres.append(w)

block = f'''{START}
  <section class="section" id="said">
    <div class="slate">
      <span class="slate__tc" data-tc>TC 38:00:00</span>
      <h2 class="slate__title">What people say</h2>
      <span class="slate__meta">006 &middot; {len(quotes)} comments</span>
    </div>
    <p class="reception__sub">Public comments, unedited, from {', '.join(wheres)}. Nothing here was asked for.
      Comments written in Arabic are marked <span class="say__ar" aria-hidden="true">ع</span> and translated.</p>
    <div class="says" aria-label="What people say">
      {strip(a, '')}
      {strip(b, ' says__row--back')}
    </div>
    <div class="reception__grid">{''.join(card(q) for q in long_)}</div>
  </section>
  {END}'''

page = open('about.html').read()
if START in page:
    page = re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END), lambda m: block, page, count=1)
else:
    anchor = '  <section class="contact" id="contact">'
    if anchor not in page:
        sys.exit('could not find the contact section to insert before')
    page = page.replace(anchor, block + '\n\n' + anchor, 1)
open('about.html', 'w').write(page)
print(f'about.html: {len(short)} on the strips, {len(long_)} as cards, {len(quotes)} in total')
