#!/usr/bin/env python3
"""Compile the film list and the reel page template into one edge module.

/reel/<code> is a viewer's own cut of the selects: an ordered subset of the
tiles, rendered at the edge with its SC/IN stamps recomputed by the same rule
the home page uses. The function that renders it needs the films and the
template as code, because a Pages Function cannot read the repository.

Everything here is lifted from index.html — titles, durations, posters (with
their content hashes), figures. Nothing is typed twice. Run after any change to
the tiles, before bin-stamp-assets.py has to be re-run for anything else.

Output: functions/_lib/reel.js  (underscore: not routed, only imported)
"""
import re, json, sys, html, os

SRC = open('index.html').read()
TPL = open('reel.tpl.html').read()

VER  = re.search(r'styles\.css\?v=(\d+)', SRC).group(1)
VERJ = re.search(r'main\.js\?v=(\d+)', SRC).group(1)
MARK = re.search(r'src="(assets/logo-96\.png\?h=[a-f0-9]+)"', SRC).group(1)

# One character per film, in DOM order. No 0/o/1-vs-l confusion: the code is
# something a producer reads out over the phone.
ALPHABET = '123456789abcdefghjkmnpqrstuvwxyz'

def field(b, pat, default=''):
    m = re.search(pat, b)
    return m.group(1) if m else default

films = []
for b in re.findall(r'<article class="tile[\s\S]+?</article>', SRC):
    dur = field(b, r'tile__dur">(\d+):(\d\d)<')
    m = re.search(r'tile__dur">(\d+):(\d\d)<', b)
    if not m:
        sys.exit('tile without a duration: ' + b[:100])
    secs = int(m.group(1)) * 60 + int(m.group(2))
    srcset = field(b, r'srcset="([^"]+)"')
    films.append({
        'title':    field(b, r'data-title="([^"]+)"'),
        'vid':      field(b, r'data-video="(\d+)"'),
        'portrait': field(b, r'data-portrait="(\w+)"') == 'true',
        'href':     field(b, r'class="tile__link" href="([^"]+)"'),
        'kind':     field(b, r'tile__kind">([^<]*)<'),
        'secs':     secs,
        'stat':     field(b, r'tile__stat"[^>]*>\s*([^<]+?)\s*<'),
        'statref':  field(b, r'tile__stat"[^>]*href="([^"]+)"'),
        'poster':   field(b, r'\bsrc="(assets/posters/[^"]+)"'),
        'srcset':   srcset,
        'alt':      field(b, r'alt="([^"]+)"'),
        'w':        field(b, r'width="(\d+)"'),
        'h':        field(b, r'height="(\d+)"'),
    })
    if not films[-1]['title'] or not films[-1]['poster']:
        sys.exit('tile missing title or poster')

if not 10 <= len(films) <= len(ALPHABET):
    sys.exit(f'unexpected film count: {len(films)}')
for n, f in enumerate(films):
    f['key'] = ALPHABET[n]

os.makedirs('functions/_lib', exist_ok=True)
out = ('// GENERATED by bin-build-reel.py from index.html + reel.tpl.html — do not edit.\n'
       f'export const VER = {json.dumps(VER)};\n'
       f'export const ALPHABET = {json.dumps(ALPHABET)};\n'
       f'export const FILMS = {json.dumps(films, ensure_ascii=False, indent=1)};\n'
       f'export const TEMPLATE = {json.dumps(TPL.replace("{{VER}}", VER).replace("{{VER_JS}}", VERJ).replace("{{MARK}}", MARK), ensure_ascii=False)};\n')
open('functions/_lib/reel.js', 'w').write(out)
print(f'functions/_lib/reel.js: {len(films)} films, keys {ALPHABET[:len(films)]}, styles v{VER}, main v{VERJ}')
